services:
  app:
    build: .
    container_name: wa-gateway
    # Ports removed to force access via Nginx Proxy Manager (more secure)
    env_file: .env
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/gateway.db
      - SESSIONS_DIR=/app/sessions
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./data:/app/data
      - ./sessions:/app/sessions
    depends_on:
      - redis
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - web-network

  redis:
    image: redis:alpine
    container_name: wa-redis
    command: >
      sh -c 'if [ -z "$${REDIS_PASSWORD}" ]; then
        redis-server --appendonly yes;
      else
        redis-server --requirepass "$${REDIS_PASSWORD}" --appendonly yes;
      fi'
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - web-network

  nginx-proxy:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: wa-nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - web-network

volumes:
  redis_data:

networks:
  web-network:
    external: true
